### ISSUE TITLE
Authentication Tasks 

### ISSUE THREAD

**Issue by AbegaM** [thevahidal/soul#149]
## Tasks 

**Features that will be executed when soul boots up**

- [x] Insert a default role in the `_roles` table after a role table is created
- [x] Insert default permissions for all tables after the `_roles_permissions` table is created

**Comment by AbegaM** [comment]
### Feb 15, 2024

## Tasks 

- [ ] Feature to update a normal user to super user 

  ```
  1. Modify the cli.js file and add an `updateuser` command 
  2. Add a function named `updateUser`
  3. Add a feature to fetch the user from the Db by using the `userId` and then update the `is_superuser` flag
  4. Add a feature to check the password strength and then hash the password and save it in the DB
  ```

**Comment by AbegaM** [comment]
### Feb 19, 2024

## Tasks 

- [ ] Feature to register users 

  1. Add a middleware function named `processCustomRequest`

     ```
     - Check if the request is sent to POST /api/tables/_users/rows
     - Call a function named modifyUserPayload
         - Check if the username is taken  ==> If true throw an error
         - Check if the password is strong ==> If not throw an error
         - Generate salt and hash the password 
         - Generate a new user payload data
         - Creat the user in the DB
         - Find the default role from the _roles table 
         - Create a role for the user in the _users_role table
         - Return the user data by removing the salt and the password
     ```

  2. Add a middleware function named `processCustomResponse`

     ```
     - Check if the request is ent to /api/tables/_users/rows
     - Call a function named removeFieldsFromUserPaylod
         - Delete the password and the salt fields 
         - Execute the next() middleware 
     ```

**Comment by IanMayo** [comment]
> Return the user data by removing the salt and the password

For `create` only a success report is returned:
https://github.com/thevahidal/soul/blob/main/docs/api/rows-examples.md#2-insert-a-new-row

**Comment by AbegaM** [comment]
> > Return the user data by removing the salt and the password
> 
> For `create` only a success report is returned: https://github.com/thevahidal/soul/blob/main/docs/api/rows-examples.md#2-insert-a-new-row

ok, i will update the task description 👍

**Comment by AbegaM** [comment]
### Feb 20, 2024

## Tasks 

- [ ] Obtain Access Token Feature

  - [ ] Add a router 

    ```
    /api/auth/token/obtain
    ```

  - [ ] Build a controller function for the feature

    - [ ] Extract the username and the password from the body

    - [ ] Find the user by using the username

    - [ ] Compare the users password with the stored password

    - [ ] Get the users role from the DB

    - [ ] Generate token 

      ```
      Create a function called generateToken
      ```

    - [ ] Send the token in the cookie

**Comment by AbegaM** [comment]
### Feb 22, 2024

## Tasks 

- [ ] Add a router for the feature 

  ```
  /api/auth/token/refresh
  ```

- [ ] Build a controller function for the feature

  - [ ] Decode the token with your `decodeToken` function
  - [ ] Check if the `subject` is `accessToken` if not throw 401 error
  - [ ] Check if the user exists in the database and if not throw 401 error
  - [ ] Generate a new access token for the user 
  - [ ] Return the access token in the cookie

**Comment by AbegaM** [comment]
### Feb 26, 2024

## Tasks 

- [ ] Add a new middleware function named `isAuthorized` 

  - [ ] Add the `isAuthorized` middleware function in all of the routers 

  - [ ] Middleware function flow

    - [ ] Check if `authMode` is true or false

      ```
      If authMode is true proceed with the authorization but if it is false then call the controller function
      ```

    - [ ] Verify the token

    - [ ] Extract the token payload

    - [ ] Check if the user is a super user

      ```
      If the user is a super user then call the controller function
      If the user is not a super user check the users role 
      ```

    - [ ] Get the users role and permission on the resource 

      ```
      If the user has permission on the resource then call the controller function
      If not then throw an error
      ```

**Comment by AbegaM** [comment]
### Feb 27, 2024

## Tasks 

- [ ] Modify the existing code to handle users with multiple roles

**Comment by AbegaM** [comment]
### Feb 28, 2024

## Tasks 

- [ ] Modify the existing code to handle users with multiple roles

  - [ ] Modify the `createDefaultTable` function

    ```
    Modify the table schema and allow multiple roles for a user
    ```

  - [ ] Modify the `obtainAccessToken` function

    ```
    Send multiple roles in the token payload
    ```

  - [ ] Modify the `isAuthorized` middleware function

    ```
    Modify the function to check multiple permissions on a specific resource
    ```

**Comment by AbegaM** [comment]
### Mar 01, 2024

## Tasks 

Fix Comments on PR, [[#148](https://github.com/thevahidal/soul/pull/148)](https://github.com/thevahidal/soul/pull/148)

- [ ] Fix typo error 
- [ ] Separate the `if` conditions for the creation of  `_roles_permissions` and  `_roles`
- [ ] Move the `default` role to the `constants` folder
- [ ] Check what happens if the `default` roles are already created

**Comment by AbegaM** [comment]
### Mar 04, 2024

## Tasks 

- [ ] Fix comments on PR [[153](https://github.com/thevahidal/soul/pull/153)](https://github.com/thevahidal/soul/pull/153)

- [ ] Fix comments on PR [[154](https://github.com/thevahidal/soul/pull/154)](https://github.com/thevahidal/soul/pull/154)

- [ ] Fix comments on PR [[156](https://github.com/thevahidal/soul/pull/156)](https://github.com/thevahidal/soul/pull/156)

- [ ] Fix comments on PR [[157](https://github.com/thevahidal/soul/pull/157)](https://github.com/thevahidal/soul/pull/157)

**Comment by AbegaM** [comment]
### Mar 05, 2024

## Tasks 

- [ ] Endpoint to update users 
- [ ] Check the validations on the `_users` endpoint 
  - [ ] Check all the `GET` , `POST` , `PUT` and `DELETE` endpoints and remove some fields like `is_superuser`, `salt` , `hashed_password` and `password` fields 
- [ ] Add a validation on the `/tables` endpoint to avoid creating reserved table names

**Comment by AbegaM** [comment]
### Mar 07, 2024

## Tasks 

- [ ] Modify the swagger setup for the new endpoints

**Comment by RubenRuCh** [comment]
Amazing job with the authentication features! Definitively improves a lot the usage of Soul

/tip 10 @AbegaM

**Comment by AbegaM** [comment]
> Amazing job with the authentication features! Definitively improves a lot the usage of Soul
> 
> /tip 10 @AbegaM

Thank you, @RubenRuCh. I appreciate your feedback.

**Comment by AbegaM** [comment]
### Mar 21, 2024

## Tasks 

- [ ] Change Boolean string values to `1/0`

- [ ] Change auth strategy

   *  Refactor the `hasAccess` `middleware function, Obtain access token API`, and the `refresh access token APIs`

**Comment by RubenRuCh** [comment]
> > Amazing job with the authentication features! Definitively improves a lot the usage of Soul
> > /tip 10 @AbegaM
> 
> Thank you, @RubenRuCh. I appreciate your feedback.

No problem! Btw were you able to setup your payment account in Opire, so I can finish the payment of the tip?

**Comment by AbegaM** [comment]
> > > Amazing job with the authentication features! Definitively improves a lot the usage of Soul
> > > /tip 10 @AbegaM
> > 
> > 
> > Thank you, @RubenRuCh. I appreciate your feedback.
> 
> No problem! Btw were you able to setup your payment account in Opire, so I can finish the payment of the tip?

Thank you, @RubenRuCh, but unfortunately, my Stripe account is not working due to some financial regulations in my country. So, you can make the donation to @IanMayo.

**Comment by RubenRuCh** [comment]
> > > > Amazing job with the authentication features! Definitively improves a lot the usage of Soul
> > > > /tip 10 @AbegaM
> > > 
> > > 
> > > Thank you, @RubenRuCh. I appreciate your feedback.
> > 
> > 
> > No problem! Btw were you able to setup your payment account in Opire, so I can finish the payment of the tip?
> 
> Thank you, @RubenRuCh, but unfortunately, my Stripe account is not working due to some financial regulations in my country. So, you can make the donation to @IanMayo.

Sorry to hear that! I'm willing to make the donation to @IanMayo but unfortunately the Opire bot has being uninstalled from the repo :cry: Could you reinstall it? @thevahidal

**Comment by thevahidal** [comment]
Hey @RubenRuCh,

Sorry, but I had to uninstall Opire. Soul's main contributors weren't too thrilled with its comments, so I had to let it go. I actually really liked the idea behind Opire, so I installed it in my other projects to keep supporting it. Hopefully, we can still grow together!

**Comment by AbegaM** [comment]
### Mar 25, 2024

## Tasks 

1. Add a logout API to remove access and refresh tokens 
   * Add a swagger documentation setup for the new API
