### ISSUE TITLE
Authentication Feature Todo lists 

### ISSUE THREAD

**Issue by AbegaM** [thevahidal/soul#155]
## Todos 

- [ ] Add unit tests for the new authentication related endpoints  
- [ ] Modify the swagger API documentation for the new authentication related endpoints 
- [ ] Add some new notes `/docs` folder 
  - [ ]  Add a note clarifying that each user in the application should have a single role assigned to them, such as 'default' or 'super_user'

- [ ] Add a note on how to test soul using the `cli` script (in `package.json`)
- [ ] We are not using special endpoints that start with `/auth` to perform `CRUD` on the `_roles`, `_roles_permissions`, and `_users_roles` so this means this resources could be updated by any user with any role
- [ ] If a user tries to access the reserved resources like `_users`, `_roles`, `_roles_permissions` and `_users_roles` while `AUTH` is set to `false` we need to throw an error in the API saying, `You can't access this endpoint while AUTH is set to false`

## Notes

1. Should we make the default table names `reserved`?

**Comment by IanMayo** [comment]
Note for @AbegaM - we're now allowing multiple roles per user.

**Comment by IanMayo** [comment]
Closing. Now implemented.
